---
title: "Graphs for presentation"
author: "kat"
date: "October 16, 2018"
output:
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rv.keep <- readRDS("rv.keepMASTER.rds")

```

### 9th grade- 573 Students in 2015

```{r}
nine <- rv.keep[rv.keep$startYear ==2015 & rv.keep$grade == 9, ]
#nine
nineU <- unique(nine$personID)
length(nineU)
```
# Create Plot of 2015 Courses Most Taken By Freshman
```{r}
length(unique(nine$personID))
courses <- as.data.frame(table(nine$courseName))
courses$class <- courses$Freq / 4
coursesh <- courses[courses$class >=100,]
coursesh <- coursesh[order(coursesh$class),]
#sort order
order <- coursesh$Var1

coursesh
physicslabel <- c("Physics", "Other", "Other", NA,NA,"Other", NA, NA, "Other", "Physics" , NA, NA )
coursesh <- cbind(coursesh, physicslabel)
library(ggplot2)
ggplot(coursesh, aes(x=Var1, y=class, fill=as.factor(coursesh$physicslabel))) +
  geom_col(fill=c("navyblue", "slategray1", "slategray1", "Grey87", "Grey87", "slategray1", "Grey87", "Grey87" , "slategray1", "navyblue", "slategray1", "slategray1" )) +
  coord_flip() +
  scale_x_discrete(limits=order)+
  theme(panel.background = element_blank(), 
        axis.ticks.y=element_blank(),
        plot.title = element_text(hjust = .13)) +
  xlab("") +
  ylab("") +
  ggtitle("2015 Most Taken Courses By Freshman")

```
### Plotting All Science courses
```{r}
# 9th graders Physics breakdown
phygraph <- nine[grep("Physics", nine$courseName), ]
phygraph_nodup <- phygraph[!duplicated(phygraph$courseduplicater),]
phygraph <- as.data.frame(table(phygraph_nodup$courseName))
phygraph2 <- phygraph[phygraph$Freq >1,]
phygraph2$nFreq <- phygraph2$Freq /4
phygraph2

# 10th graders Chemistry breakdown
ten <- rv.keep[rv.keep$startYear ==2016 & rv.keep$grade == 10, ]
phygraph <- ten[grep("Chemistry", ten$courseName), ]
phygraph_nodup <- phygraph[!duplicated(phygraph$courseduplicater),]
phygraph <- as.data.frame(table(phygraph_nodup$courseName))
phygraph1 <- phygraph[phygraph$Freq >1,]
phygraph1$nFreq <- phygraph1$Freq /4
phygraph1

## Juniors
eleven <- rv.keep[rv.keep$startYear ==2017 & rv.keep$grade == 11, ]
phygraph <- eleven[grep("Biology", eleven$courseName), ]
phygraph_nodup <- phygraph[!duplicated(phygraph$courseduplicater),]
phygraph <- as.data.frame(table(phygraph_nodup$courseName))
phygraph3 <- phygraph[phygraph$Freq >1,]
phygraph3$nFreq <- phygraph3$Freq /4
phygraph3

```


```{r}
library(dplyr)
bind1<- rbind(phygraph2, phygraph1)
bind1 <- rbind(bind1, phygraph3)
#bind1
c <- as.factor(c("P", "P", "C", "C", "C", "B", "B", "B", "B"))
bind1 <- cbind(bind1, c)
bind1 <- bind1[order(-bind1$nFreq),]

#bind1
bind1_ordered <- bind1 %>% arrange(c, nFreq)
order <- bind1_ordered$Var1
ggplot(bind1, aes(x=Var1, y=nFreq, fill=c))+
  geom_col()+
  coord_flip()+
  scale_x_discrete(limits=order)+
  xlab("")+
  ylab("")+
  ggtitle("Science Course Options By Grade Level")+
  theme(panel.background = element_blank(), 
        axis.ticks.y=element_blank(),
        plot.title = element_text(hjust = .17))+
   scale_fill_manual(values=c("navyblue", "slategray1", "Grey87"), 
                     labels=c("Junior", "Sophomore", "Freshman"),
                     name="Grade Level")+
  guides(fill=guide_legend(reverse=TRUE))
```

